"""
Build the MapLibre webmaps from the fetched data.

For every city folder in data/ that has a boundary and at least one
completed tile with images, writes maps/<slug>/ (index.html, points.geojson,
boundary.geojson); then writes the index map (maps/index.html,
maps/cities.json, maps/cities.geojson) that opens them. The basemaps are
OpenFreeMap's Positron, Dark and Liberty ("Regular") styles.

Usage:
    python scripts/build_webmaps.py                  # data/ -> maps/
    python scripts/build_webmaps.py --data-dir data --out maps

Preview: python -m http.server -d maps  (then open http://localhost:8000)
"""

import argparse
import html
import json
import math
import os
import shutil
from datetime import datetime, timezone
from pathlib import Path

import geopandas as gpd
import pandas as pd
from shapely.geometry import mapping, shape

REPO_ROOT = Path(__file__).resolve().parent.parent
TEMPLATES = Path(__file__).resolve().parent / "webmap"

# marks the city folders created by this script (only these are ever removed)
GENERATED_MARKER = ".generated"

# boundary simplification tolerances, in degrees (~5 m and ~50 m)
CITY_BOUNDARY_TOLERANCE = 0.00005
INDEX_BOUNDARY_TOLERANCE = 0.0005


def write_json(data, path):
    tmp = f"{path}.tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
    os.replace(tmp, path)


def _round(value, digits):
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return None
    return round(float(value), digits)


def load_city(city_dir):
    """The data of a city folder, or None if it has no image to map yet."""
    boundary_path = city_dir / "boundary.geojson"
    tiles = sorted((city_dir / "tiles").glob("*.parquet"))
    if not boundary_path.exists() or not tiles:
        return None

    frames = [gpd.read_parquet(path) for path in tiles]
    frames = [f for f in frames if not f.empty]
    if not frames:
        return None
    points = pd.concat(frames, ignore_index=True).drop_duplicates(subset="id")

    with open(boundary_path, encoding="utf-8") as f:
        feature = json.load(f)["features"][0]
    progress = {}
    if (city_dir / "progress.json").exists():
        with open(city_dir / "progress.json", encoding="utf-8") as f:
            progress = json.load(f)

    properties = feature["properties"]
    display_name = properties.get("display_name") or properties.get("place") or city_dir.name
    return {
        "slug": city_dir.name,
        "name": display_name.split(",")[0].strip(),
        "display_name": display_name,
        "boundary": shape(feature["geometry"]),
        "points": points,
        "progress": progress,
        "city_dir": city_dir,
    }


def city_stats(city):
    points, summary = city["points"], city["progress"].get("summary", {})
    dates = points["captured_at"].dropna()
    return {
        "images": int(len(points)),
        "vegetation_median": _round(points["vegetation_percent"].median(), 1),
        "vegetation_mean": _round(points["vegetation_percent"].mean(), 1),
        "date_min": dates.min().strftime("%Y-%m-%d") if len(dates) else None,
        "date_max": dates.max().strftime("%Y-%m-%d") if len(dates) else None,
        "tiles_completed": summary.get("completed"),
        "tiles_total": summary.get("big_tiles"),
        "updated": (city["progress"].get("updated_at") or "")[:10] or None,
    }


def points_geojson(points):
    features = []
    for row in points.itertuples(index=False):
        captured = row.captured_at
        features.append({
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [round(row.lon, 6), round(row.lat, 6)]},
            "properties": {
                "id": str(row.id),
                "veg": _round(row.vegetation_percent, 1),
                "date": captured.strftime("%Y-%m-%d") if not pd.isna(captured) else None,
                "h": _round(getattr(row, "h", None), 1),
            },
        })
    return {"type": "FeatureCollection", "features": features}


def render(template_name, replacements):
    text = (TEMPLATES / template_name).read_text(encoding="utf-8")
    for key, value in replacements.items():
        text = text.replace(key, value)
    return text


def config_json(config):
    # safe inside <script type="application/json">
    return json.dumps(config, ensure_ascii=False).replace("</", "<\\/")


def build_city(city, out_dir):
    city_out = out_dir / city["slug"]
    city_out.mkdir(parents=True, exist_ok=True)
    (city_out / GENERATED_MARKER).write_text("generated by scripts/build_webmaps.py\n", encoding="utf-8")

    stats = city_stats(city)
    boundary = city["boundary"].simplify(CITY_BOUNDARY_TOLERANCE, preserve_topology=True)
    minx, miny, maxx, maxy = city["boundary"].bounds
    city_dir = city.get("city_dir")
    has_segments = False
    has_voronoi = False

    if city_dir:
        seg_file = city_dir / "segments.parquet"
        vor_file = city_dir / "voronoi.parquet"
        if seg_file.exists():
            try:
                segs = gpd.read_parquet(seg_file)
                if not segs.empty:
                    segs_simple = segs.copy()
                    segs_simple["geometry"] = segs_simple.geometry.simplify(0.00002, preserve_topology=True)
                    write_json(json.loads(segs_simple.to_json(drop_id=True)), city_out / "segments.geojson")
                    has_segments = True
            except Exception as e:
                print(f"   warning: failed to write segments.geojson: {e}")

        if vor_file.exists():
            try:
                vor = gpd.read_parquet(vor_file)
                if not vor.empty:
                    vor_simple = vor.copy()
                    vor_simple["geometry"] = vor_simple.geometry.simplify(0.00005, preserve_topology=True)
                    write_json(json.loads(vor_simple.to_json(drop_id=True)), city_out / "voronoi.geojson")
                    has_voronoi = True
            except Exception as e:
                print(f"   warning: failed to write voronoi.geojson: {e}")

    config = {
        "slug": city["slug"],
        "name": city["name"],
        "display_name": city["display_name"],
        "bounds": [minx, miny, maxx, maxy],
        "stats": stats,
        "has_segments": has_segments,
        "has_voronoi": has_voronoi,
    }

    write_json(points_geojson(city["points"]), city_out / "points.geojson")
    write_json(
        {"type": "FeatureCollection", "features": [{"type": "Feature", "properties": {}, "geometry": mapping(boundary)}]},
        city_out / "boundary.geojson",
    )
    (city_out / "index.html").write_text(
        render("city.html", {"__TITLE__": html.escape(city["name"]), "__CONFIG__": config_json(config)}),
        encoding="utf-8",
    )

    center = city["boundary"].representative_point()
    return {**config, "center": [round(center.x, 6), round(center.y, 6)]}


def build(data_dir, out_dir):
    data_dir, out_dir = Path(data_dir), Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    entries, index_features = [], []
    for city_dir in sorted(p for p in data_dir.iterdir() if p.is_dir()) if data_dir.exists() else []:
        city = load_city(city_dir)
        if city is None:
            print(f"   {city_dir.name}: no data yet, skipped")
            continue
        entry = build_city(city, out_dir)
        entries.append(entry)
        index_features.append({
            "type": "Feature",
            "properties": {"slug": entry["slug"], "name": entry["name"]},
            "geometry": mapping(city["boundary"].simplify(INDEX_BOUNDARY_TOLERANCE, preserve_topology=True)),
        })
        print(f"🗺️  {entry['slug']}: {entry['stats']['images']} images")

    # remove the maps of cities that no longer have data
    built = {e["slug"] for e in entries}
    for folder in out_dir.iterdir():
        if folder.is_dir() and (folder / GENERATED_MARKER).exists() and folder.name not in built:
            shutil.rmtree(folder)
            print(f"   {folder.name}: removed (no data anymore)")

    assets = out_dir / "assets"
    assets.mkdir(exist_ok=True)
    for name in ("map.js", "style.css"):
        shutil.copyfile(TEMPLATES / name, assets / name)

    write_json(entries, out_dir / "cities.json")
    write_json({"type": "FeatureCollection", "features": index_features}, out_dir / "cities.geojson")
    updated = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    (out_dir / "index.html").write_text(render("index.html", {"__UPDATED__": updated}), encoding="utf-8")
    print(f"✅ {len(entries)} city maps and the index written to {out_dir}")
    return entries


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--data-dir", default=str(REPO_ROOT / "data"), help="Fetched data (default: data/)")
    parser.add_argument("--out", default=str(REPO_ROOT / "maps"), help="Output folder of the site (default: maps/)")
    args = parser.parse_args(argv)
    build(args.data_dir, args.out)


if __name__ == "__main__":
    main()
